name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - requests=2.31.0
  - mlflow=2.6.0
  - pip:
      - wandb==0.15.10
      - git+https://github.com/kaysunphd/machine-learning-pipeline.git#egg=wandb-utils&subdirectory=components
